server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /.well-known/apple-app-site-association {
    default_type application/json;
    try_files $uri =404;
  }

  location = /.well-known/assetlinks.json {
    default_type application/json;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
