export type {
  AssignmentDto as Assignment,
  AssignmentChatDto as AssignmentChat,
  AssignmentChatMessageDto as AssignmentChatMessage,
  GiftIdeaDto as GiftIdea,
  GiftIdeaUserDto as GiftIdeaUser,
  GroupDto as Group,
  GroupMemberDto as GroupMember,
  GroupOwnerDto as GroupOwner,
} from '../../../api/src/contracts/api';
